mqtt:
  host: test.mosquitto.org
  port: 1883
  user: ""
  password: ""
  topic_prefix: pimqttgpio/mydevice
  protocol: 3.1.1

gpio_modules:
  - name: stdio
    module: stdio

digital_inputs:
  - name: button
    module: stdio
    pin: 21
    on_payload: "ON"
    off_payload: "OFF"
    pullup: yes
    pulldown: no
    inverted: yes

digital_outputs:
  - name: bell
    module: stdio
    pin: 20
    on_payload: "ON"
    off_payload: "OFF"
    publish_initial: yes
    initial: high
